// 특정 상품 댓글 등록
###
POST http://localhost:3000/comments/products/4f9a6c4c-0845-4f8a-8b22-cfae0152c321
Content-Type: application/json

{
  "content": "가벼워요"
}

// 특정 게시물 댓글 등록
###
POST http://localhost:3000/comments/articles/e5a4c817-40f8-41f4-812a-9eae9c33c3b0
Content-Type: application/json

{
  "content": "환타지 쵝오"
}


// 댓글 목록 조회: cursor 기반
// 첫 조회: offset=0, cursor=undefined
// 모든 댓글 type = all, 상품 댓글 type=product, 게시물 댓글 type=article
###
GET http://localhost:3000/comments?type=all 
###
GET http://localhost:3000/comments?type=product
###
GET http://localhost:3000/comments?type=article
###
GET http://localhost:3000/comments?limit=10&cursor=2fd019db-81b9-4f64-bb0f-0a7adf41e7e5
###
// 댓글 목록 조회: content로 filtering
GET http://localhost:3000/comments?content=배터리



// 댓글 1개 조회
###
GET http://localhost:3000/comments/15b6d80f-06f9-4ef9-b6c9-6d3d9e43493d

// 댓글 1개 수정
###
PATCH http://localhost:3000/comments/15b6d80f-06f9-4ef9-b6c9-6d3d9e43493d
Content-Type: application/json

{
  "content": "OST가 너무 감동적이에요."
}

// 댓글 1개 삭제
###
DELETE http://localhost:3000/comments/2ea66daa-4991-4e55-99eb-ac7c4bc5e3b9