// 특정 상품 댓글 등록
###
POST http://localhost:3000/comments/products/de52a1db-1a1c-4ef8-9e6a-8f1d7c4ef05a
Content-Type: application/json

{
  "content": "아이폰은 진리."
}

// 특정 게시물 댓글 등록
###
POST http://localhost:3000/comments/articles/4c2b5e3f-8af1-4c44-84b7-1cb4e2b9272c
Content-Type: application/json

{
  "content": "예상치 못한 결말이었어요."
}


// 댓글 목록 조회: cursor 기반
// 첫 조회: offset=0, cursor=undefined
###
GET http://localhost:3000/comments
###
GET http://localhost:3000/comments?limit=10&cursor=4a6e3d8c-5132-4e2a-b9b1-b8b9b8e1a7f9
###
// 댓글 목록 조회: content로 filtering
GET http://localhost:3000/comments?content=충격



// 중고마켓 상품 전체에 대한 댓글 목록 조회, cursor 기반
###
GET http://localhost:3000/comments/products


// 자유게시판 모든 게시물에 대한 댓글 목록 조회, cursor 기반
###
GET http://localhost:3000/comments/articles

// 댓글 1개 조회
###
GET http://localhost:3000/comments/2fa7f1de-7088-4b3d-9c5f-64b707a93471

// 댓글 1개 수정
###
PATCH http://localhost:3000/comments/8319b625-8515-42cf-beac-f546c6aa298c
Content-Type: application/json

{
  "content": "너무 비싸요"
}

// 댓글 1개 삭제
###
DELETE http://localhost:3000/comments/8319b625-8515-42cf-beac-f546c6aa298c

