@baseUrl = http://localhost:3000

//------------------------상품 이미지 APIs
GET {{baseUrl}}/images/products/29
###

// 토큰 인증 + 인가 (상품을 등록한 유저만 가능)
###
POST {{baseUrl}}/images/products/29
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="iphone17pro.png"
Content-Type: image/png

< ./images/product/iphone17pro.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/products/29




//------------------------ 게시물 이미지 APIs
// 전망좋은 방  
// 사촌 비니 

###
GET {{baseUrl}}/images/articles/27

###
POST {{baseUrl}}/images/articles/21
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="aRoomWithaView.png"
Content-Type: image/png

< ./images/article/aRoomWithaView.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/articles/21


//------------------------ 사용자 이미지 APIs

###
GET {{baseUrl}}/images/users/1

###
POST {{baseUrl}}/images/users/2
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="Frodo2.png"
Content-Type: image/png

< ./images/user/Frodo2.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/users/1

