@baseUrl = http://localhost:3000

// 상품 목록 조회
// 페이지네이션: offset 기반 (default 값: offset=0, limit=undefined)
// 조회순: order=recent(default)/oldest
GET {{baseUrl}}/products
###
GET {{baseUrl}}/products?order=oldest
###
GET {{baseUrl}}/products?order=oldest&offset=4

// 상품 목록 조회
// 조건 검색: name and/or description에 포함된 단어
###
GET {{baseUrl}}/products?name=Pro
###
GET {{baseUrl}}/products?description=스마트
###
GET {{baseUrl}}/products?name=Pro&description=성능


// 상품 상세 조회, 좋아요, 등록 인증 필요
###
GET {{baseUrl}}/products/26


###
POST {{baseUrl}}/products/26/like
###
POST {{baseUrl}}/products/26/like/cancel

###
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "iPhone 17 Pro",
  "description": "최신 아이폰",
  "price": 1790000,
  "tags": ["전자제품", "스마트폰"]
}

// 상품 수정과 삭제: 인증, 인가 필요
###
PATCH {{baseUrl}}/products/32
Content-Type: application/json

{
  "description": "2025년 10월 한국에 발매 시작한 최신 아이폰으로 8배 광학줌을 가진 후면 카메라가 압권입니다.",
  "price": 1790000,
  "tags": ["전자제품", "스마트폰", "경량 케이스"]
}

###
DELETE {{baseUrl}}/products/32

