@baseUrl = http://localhost:3000

GET {{baseUrl}}/users

###
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "email": "user9@example.com",
  "nickname": "user9",
  "password": "password9"
}

// 등록할 때 사용자 이미지도 함께 등록하도록 변경할 예정
# POST {{baseUrl}}/users/register
# Content-Type: multipart/form-data; boundary=MyBoundary
 
# --MyBoundary
# Content-Disposition: form-data; name="data"
# Content-Type: application/json

# {
#   "email": "Frodo@example.com",
#   "nickname": "Frodo",
#   "password": "Frodo"
# }

# --MyBoundary
# Content-Disposition: form-data; name="image"; filename="Frodo2.png"
# Content-Type: image/png

# < ./images/user/Frodo2.png
# --MyBoundary--

###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "password1"
}

###
POST {{baseUrl}}/users/logout



// 토큰 발행, 확인
###
POST {{baseUrl}}/users/tokens/refresh
###
GET {{baseUrl}}/users/tokens/view



// 토큰 인증이 필요한 User APIs
###
GET {{baseUrl}}/users/info
###
PATCH {{baseUrl}}/users/info/edit
Content-Type: application/json

{ 
  "nickname": "Toshil" 
}

// 나의 정보 수정할 때 이미지도 수정할 수 있도록 변경할 예정
# PATCH {{baseUrl}}/users/MyInfo/edit
# Content-Type: multipart/form-data; boundary=MyBoundary
 
# --MyBoundary
# Content-Disposition: form-data; name="data"
# Content-Type: application/json

# { 
#   "nickname": "user2" 
# }

# --MyBoundary
# Content-Disposition: form-data; name="image"; filename="Frodo1.png"
# Content-Type: image/png

# < ./images/user/Frodo1.png
# --MyBoundary--



###
PATCH {{baseUrl}}/users/info/password/change
Content-Type: application/json

{
  "password_now": "password88",
  "password_new": "password8"
}

###
GET {{baseUrl}}/users/products
###
GET {{baseUrl}}/users/articles 
###
GET {{baseUrl}}/users/like/products
###
GET {{baseUrl}}/users/like/articles