GET http://localhost:3000/articles?order=newest

###
GET http://localhost:3000/articles/b5d98b7b-9258-4d75-a510-decfacea93d6

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "New Article",
  "content": "This is the content of the new article."
}

###
PATCH  http://localhost:3000/articles/1e0a52ff-8fce-424a-95ca-a4b7df348e7a
Content-Type: application/json

{
  "title": "Updated Article Title",
  "content": "Updated content of the article."
}   

###
DELETE http://localhost:3000/articles/1e0a52ff-8fce-424a-95ca-a4b7df348e7a
