// 상품 댓글 목록 조회
###
GET http://localhost:4000/comments/product/88b8a9fe-f341-4e68-91a0-baaa7fffc523

// 상품 댓글 생성
###
POST http://localhost:4000/comments/product/88b8a9fe-f341-4e68-91a0-baaa7fffc523
Content-Type: application/json

{
    "content": "댓글을 달아버려"
}

// 게시글 댓글 목록 조회
###
GET http://localhost:4000/comments/article/1d71847c-933a-40ee-aa18-20e4e088686a

// 게시글 댓글 생성
###
POST http://localhost:4000/comments/article/2e8bee57-2983-4b26-8593-e5371fc2a55e
Content-Type: application/json

{
    "content": "댓글을 달아"
}

// 댓글 수정
###
PATCH http://localhost:4000/comments/7686fd3c-d076-4af9-8932-4a5db2c816a2
Content-Type: application/json

{
    "content": "수정해"
}

// 댓글 삭제
###
DELETE http://localhost:4000/comments/7686fd3c-d076-4af9-8932-4a5db2c816a2