### 유저 등록
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email" : "kim@gmail.com",
  "nickname" : "김진호",
  "password": "1234"
}

### 유저 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "kim@gmail.com",
  "nickname" : "김진호",
  "password": "1234"
}

### 유저 로그아웃
POST http://localhost:3000/auth/logout
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzY0MzI1OTY2LCJleHAiOjE3NjQzOTc5NjZ9.NqGU7lR0yfaYZM7gE8O-PCGUhr_ZyHX5bf3Kn3TZTWk;




### refresh 토큰으로 access_token, refresh_token 재발급
POST http://localhost:3000/auth/refresh
Content-Type: application/json
Cookie: refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzY0MzI1OTY2LCJleHAiOjE3NjQ0MTIzNjZ9.oDKEkIiL0vuLmEhhMJFibuIToSOhXdT2EXCf-kHmd5E;



###
// GET http://localhost:3000/auth/{userId}
# GET http://localhost:3000/auth/6
# Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzY0MzI2MDIxLCJleHAiOjE3NjQzOTgwMjF9.h6-MSEgxyAoeMJtaqJYKw-fC0Az7Bk1TExxhht_c9Ok;


