########## 상품(Product) ########## 

// 상품 댓글 등록 http://localhost:3000/products/{productId}/comments
POST http://localhost:3000/products/2/comments
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;

{
  "content" : "좋은 축구공이네요."
}

###
// 상품 댓글 조회 http://localhot:3000/products/{productId}/comments
# GET http://localhost:3000/products/{productId}/comments


###
// 상품 댓글 수정 http://localhost:3000/comments/products/{commentId}
PATCH http://localhost:3000/comments/products/2
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;

{
  "content" : "사용해보니 상품이 조금 별로네요. 별 3개 드립니다.22 "
}

###
// 상품 댓글 삭제 http://localhost:3000/comments/products/{commentId}
DELETE http://localhost:3000/comments/products/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;




########## 기사(Article) ##########

// 상품 댓글 등록 http://localhost:3000/articles/{articleId}/comments
POST http://localhost:3000/articles/1/comments
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;

{
  "content" : "기사가 너무 감명 깊네요.. 별 4개 드립니다."
}


###
// 기사(Article) 댓글 수정 http://localhost:3000/comments/articles/{commentId}
PATCH http://localhost:3000/comments/articles/4
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;


{
  "content" : "기사가 나쁘지 않네요."
}


###
// 기사(Article) 댓글 삭제 http://localhost:3000/comments/articles/{commentId}
DELETE http://localhost:3000/comments/articles/4
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;


###
// 기사(Article) 댓글 조회 http://localhot:3000/articles/{articleId}/comments
# GET http://localhost:3000/articles/{articleId}/comments

