##################################### 상품(Product) #####################################

// 상품 댓글 등록 http://localhost:3000/products/{productId}/comments
POST http://localhost:3000/products/c47d9797-80a8-4365-b378-1999e04854f8/comments
Content-Type: application/json

{
  "content" : "상품이 너무 좋습니다. 별 5개 드립니다."
}
###


// 상품 댓글 조회 http://localhot:3000/products/{productId}/comments
GET http://localhost:3000/products/c47d9797-80a8-4365-b378-1999e04854f8/comments
###



// 상품 댓글 수정 http://localhost:3000/comments/products/{commentId}
PATCH http://localhost:3000/comments/products/2228b09c-e8ae-41fa-8bbf-a955a947d6d7
Content-Type: application/json

{
  "content" : "사용해보니 상품이 조금 별로네요. 별 3개 드립니다. "
}


###
// 상품 댓글 삭제 http://localhost:3000/comments/products/{commentId}
DELETE http://localhost:3000/comments/products/2228b09c-e8ae-41fa-8bbf-a955a947d6d7








##################################### 기사(Article) #####################################

// 상품 댓글 등록 http://localhost:3000/articles/{articleId}/comments
POST http://localhost:3000/articles/fe8bba38-ab37-4871-9ab3-b32b79409219/comments
Content-Type: application/json

{
  "content" : "기사가 너무 감명 깊네요.. 별 4개 드립니다."
}
###


// 기사(Article) 댓글 조회 http://localhot:3000/articles/{articleId}/comments
GET http://localhost:3000/articles/fe8bba38-ab37-4871-9ab3-b32b79409219/comments
###


// 기사(Article) 댓글 수정 http://localhost:3000/comments/articles/{commentId}
PATCH http://localhost:3000/comments/products/3ea7e61d-aa31-4ba8-a163-8c765fd33cf2
Content-Type: application/json

{
  "content" : "읽다 보니 기사가 더 깊은 뜻이 있네요. 별 5개 드립니다. "
}


###
// 기사(Article) 댓글 삭제 http://localhost:3000/comments/articles/{commentId}
DELETE http://localhost:3000/comments/products/3ea7e61d-aa31-4ba8-a163-8c765fd33cf2



