###
// 상품 등록 
// POST http://localhost:3000/products
POST http://localhost:3000/products
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NjAwODk4LCJleHAiOjE3NjU2NzI4OTh9.3GolPNJDxlQFAOee3VUQRzhW0A_qBGAYARbAicWhTnc;


{
  "name": "축구공",
  "description": "손흥민 축구공",
  "price": 30000,
  "tags": "SPORTS"
}

###
// 상품 수정 
// PATCH http://localhost:3000/products/{productId}
PATCH http://localhost:3000/products/1
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NjAwODk4LCJleHAiOjE3NjU2NzI4OTh9.3GolPNJDxlQFAOee3VUQRzhW0A_qBGAYARbAicWhTnc;


{
  "description": "화장품",
  "price" : 6400
}


###
// 상품 삭제 
// DELETE http://localhost:3000/products/{productId}
DELETE http://localhost:3000/products/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NjAwODk4LCJleHAiOjE3NjU2NzI4OTh9.3GolPNJDxlQFAOee3VUQRzhW0A_qBGAYARbAicWhTnc;


###
// 로그인 한 유저의 특정 상품 상세조회 
// GET http://localhost:3000/products/{productId} 
GET http://localhost:3000/products/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY1NjAwODk4LCJleHAiOjE3NjU2NzI4OTh9.3GolPNJDxlQFAOee3VUQRzhW0A_qBGAYARbAicWhTnc;



###
// 로그인 안 한 유저의 상품 조회 (검색, 페이지네이션) 좋아요는 못 봄
// GET http://localhost:3000/products?offset=0&limit=10&order=newest&keyword=nike
GET http://localhost:3000/products?offset=0&limit=10&order=newest



###
// 로그인 한 유저가 상품에 '좋아요' 클릭
// POST http://localhost:3000/products/{productId}/like
POST http://localhost:3000/products/2/like
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc2NDI4OTYxOSwiZXhwIjoxNzY0MzYxNjE5fQ.ZhvbfnuoCADq6F2rf_H8td0LB8gavIZMogoLQt_9Dc8;


###
// 로그인 한 유저가 상품에 '좋아요 취소' 클릭
// DELETE http://localhost:3000/products/{productId}/like
DELETE http://localhost:3000/products/10/like
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTc2NDI4OTYxOSwiZXhwIjoxNzY0MzYxNjE5fQ.ZhvbfnuoCADq6F2rf_H8td0LB8gavIZMogoLQt_9Dc8;



