###
// 상품 등록
POST http://localhost:3000/products
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;

{
  "name": "축구공",
  "description": "손흥민 축구공",
  "price": 30000,
  "tags": "SPORTS"
}

###
// 상품 수정 PATCH http://localhost:3000/products/{productId}
PATCH http://localhost:3000/products/1
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;

{
  "name": "화장품",
  "description": "썬크림",
  "price" : 6400
}


###
// 상품 삭제 DELETE http://localhost:3000/products/{productId}
DELETE http://localhost:3000/products/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;



###
// 로그인 한 유저가 상품에 '좋아요' 클릭
// http://localhost:3000/products/{productId}/like
POST http://localhost:3000/products/2/like
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;


###
// 로그인 한 유저가 상품에 '좋아요 취소' 클릭
// http://localhost:3000/products/{productId}/like
DELETE http://localhost:3000/products/2/like
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;


### 로그인 한 유저가 등록한 상품 조회
// 상품 조회 GET http://localhost:3000/products/{productId}
GET http://localhost:3000/products/2
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzY0MzI2NTUzLCJleHAiOjE3NjQzOTg1NTN9.GrCQUqDy4OilT66n8j0Bb0FTzm-F0ScLNtHY6v_Wzlw;


###
// 상품 목록 조회
# GET http://localhost:3000/products?keyword=마스크&offset=0&limit=3&order=newest

