###
// 유저 조회 GET http://localhost:3000/users/me
// 로그인한 유저가 본인이 등록한 상품, 기사 데이터 보기 (마이페이지)
GET http://localhost:3000/users/me
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY1NzAxOTcxLCJleHAiOjE3NjU3NzM5NzF9.qd3IxrBMtTmnJoyqueer6WmxtISVgGTwuoCVEerx0Dw;

###

// 유저가 자신의 정보를 수정
PATCH http://localhost:3000/users/me
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY1NzAxOTcxLCJleHAiOjE3NjU3NzM5NzF9.qd3IxrBMtTmnJoyqueer6WmxtISVgGTwuoCVEerx0Dw;

{
  "nickname" : "김진영"
}

###
// 유저가 자신의 비밀번호를 변경
PATCH http://localhost:3000/users/me/password
Content-Type: application/json
Cookie: access-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY1NzAxOTcxLCJleHAiOjE3NjU3NzM5NzF9.qd3IxrBMtTmnJoyqueer6WmxtISVgGTwuoCVEerx0Dw;

{
  "password" : "6666"
}
